[package]
name = "passe-cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "passe"

[dependencies]
passe = { path = "../core" }
clap = { version = "3.2" }
anyhow = "1"
rpassword = "7.0"
log = "0.4"
shellexpand = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clipboard = "0.5"
rprompt = "1"
ureq = { version = "2", features = ["json"] }
