[package]
name = "passe"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.20.0-alpha.1"
anyhow = "1"
log = "0.4"
md5 = "0.7"
shellexpand = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
